# Generated by Django 4.2.25 on 2025-10-08 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuizResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_type', models.CharField(choices=[('divorce', 'Развод'), ('child_support', 'Алименты'), ('property', 'Раздел имущества'), ('other', 'Другое')], max_length=50)),
                ('details', models.TextField()),
                ('full_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('consultation_method', models.CharField(choices=[('office', 'В офисе'), ('phone', 'По телефону'), ('whatsapp', 'WhatsApp'), ('home', 'Выезд на дом')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
