# Generated by Django 4.2.25 on 2025-10-04 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizresponse',
            name='details',
        ),
        migrations.AddField(
            model_name='quizresponse',
            name='question_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quizresponse',
            name='question_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quizresponse',
            name='question_3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='quizresponse',
            name='question_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quizresponse',
            name='full_name',
            field=models.CharField(max_length=150),
        ),
    ]
